config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/login'

  resources :quests
  resources :npcs

  get 'spells', to: 'spells#index'
  get 'spells/:id', to: 'spells#show'

  get 'monsters', to: 'monsters#index'
  get 'monsters/:id', to: 'monsters#show'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :discovered, -> { where(discovered: true) }
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :actions
  has_many :legendaries
  has_many :specials

  accepts_nested_attributes_for :actions
  accepts_nested_attributes_for :legendaries
  accepts_nested_attributes_for :specials

  def experience
    lookup = {"1/8" => 25,"1/4" => 50,"1/2" => 100,"1" => 200,"2" => 450,"3" => 700,"4" => 1100,"5" => 1800,"6" => 2300,"7" => 2900,"8" => 3900,"9" => 5000,"10" => 5900,"11" => 7200,"12" => 8400,"13" => 10000,"14" => 11500,"15" => 13000,"16" => 15000,"17" => 18000,"18" => 20000,"19" => 22000,"20" => 25000,"21" => 33000,"22" => 41000,"23" => 50000,"24" => 62000,"30" => 155000}
    return lookup[challenge_rating]
  end

  validates_presence_of :name, :challenge_rating, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma
end

app/models/monster/action.rb
class Monster::Action < ApplicationRecord
  belongs_to :monster

  validates_presence_of :name, :desc
end

app/models/monster/legendary.rb
class Monster::Legendary < ApplicationRecord
  belongs_to :monster

  def damage_dice=(param)
  end
  
  validates_presence_of :name, :desc
end

app/models/monster/special.rb
class Monster::Special < ApplicationRecord
  belongs_to :monster

  def damage_dice=(param)
  end
  
  validates_presence_of :name, :desc
end

app/models/npc.rb
class Npc < ApplicationRecord
  has_and_belongs_to_many :quests
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  
end

app/models/quest.rb
class Quest < ApplicationRecord
  has_and_belongs_to_many :npcs
  accepts_nested_attributes_for :npcs
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true

  def npcs_attributes=(attributes)
    npc_ids = attributes.values.map {|hash| hash[:id] }
    npc_ids = npc_ids.select { |value| value != nil }
    self.npcs = Npc.where(id: npc_ids)
  end
end

app/models/spell.rb
class Spell < ApplicationRecord
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password|
        session[:user] = 'admin' if user_name == 'admin' && password == 'password'
      end
    end

    def admin?
      session[:user] == 'admin'
    end

    def requireAuth(item)
      if not admin? and not item.discovered
        authenticate
      end
    end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

  def index
    @monsters = Monster.all
  end

  def show
    @monster = Monster.find(params[:id])
    puts @monster.actions.empty?
    puts "aaaaaaaaaaaaaaaaaaaaaa"
  end

end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController

  def index
    @npcs = Npc.all
  end

  def show
    @npc = Npc.find(params[:id])
    requireAuth(@npc)
  end

  def new
    @npc = Npc.new()
  end

  def edit
    @npc = Npc.find(params[:id])
    requireAuth(@npc)
  end

  def create
    @npc = Npc.new(npc_params)

    if @npc.save
      redirect_to @npc
    else
      render 'new'
    end
  end

  def update
    @Npc = Npc.find(params[:id])
    requireAuth(@npc)

    if @Npc.update(npc_params)
      redirect_to @Npc
    else
      render 'edit'
    end
  end

  def destroy
    @Npc  = Npc.find(params[:id])
    requireAuth(@npc)

    @Npc.destroy
    redirect_to npcs_path
  end

  private
    def npc_params
      params.require(:npc).permit(:name, :description, :discovered)
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  def index
    @quests = Quest.all
  end

  def show
    @quest = Quest.find(params[:id])
    requireAuth(@quest)
  end

  def new
    @quest = Quest.new()
    2.times { @quest.npcs.build }
  end

  def edit
    @quest = Quest.find(params[:id])
    requireAuth(@quest)

    @quest.npcs.build
  end

  def create
    @quest = Quest.new(quest_params)

    if @quest.save
      redirect_to @quest
    else
      render 'new'
    end
  end

  def update
    @quest = Quest.find(params[:id])
    requireAuth(@quest)

    if @quest.update(quest_params)
      redirect_to @quest
    else
      render 'edit'
    end
  end

  def destroy
    @quest  = Quest.find(params[:id])
    requireAuth(@quest)

    @quest.destroy
    redirect_to quests_path
  end

  private
    def quest_params
      params.require(:quest).permit(:name, :description, :discovered, npcs_attributes: [:id])
    end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController

  def index
    @spells = Spell.all
  end

  def show
    @spell = Spell.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate, only: :login

  def index
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    session[:user] == 'admin'
  end

  def permitted(model)
    if admin?
      return model
    else
      return model.discovered
    end
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/monsters/_monster.html.erb

<h2><%= @monster.name %></h2>
<br>

<div class="container">
  <div class="row">
    <% [:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma].each do |stat| %>
      <div class="col">
        <%= stat.capitalize %>
      </div>
    <% end %>
  </div>
  <div class="row">
    <% [:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma].each do |stat| %>
      <div class="col">
        <% val = @monster.send(stat) %>
        <%= val %> (<%= sprintf("%+d", val/2-5) %>)
      </div>
    <% end %>
  </div>
</div>
<br>

<p>
  <strong>Challenge Rating: </strong>
  <%= @monster.challenge_rating %> (<%= @monster.experience %> XP)
</p>

<% notShow = [:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma,
  :name, :challenge_rating, :actions, :id, :created_at, :updated_at] %>
<% (@monster.attributes.reject {|k,v| notShow.include? k.to_sym or v==nil or v=="" } ).each do |key, value| %>
  <p>
    <strong><%= key %>:</strong>
    <%= value %>
  </p>
<% end %>

<% if not @monster.specials.empty? %>
  <strong>Special Abilities:</strong>
  <% @monster.specials.each do |special|%>
    <div class="card">
      <div class="card-header">
        <%= special.name %>
      </div>
      <div class="card-body">
        <%= special.desc %>
      </div>
    </div>
    <br>
  <% end %>
<% end %>

<% if not @monster.actions.empty? %>
  <strong>Actions:</strong>
  <% @monster.actions.each do |action|%>
    <div class="card">
      <div class="card-header">
        <%= action.name %>
      </div>
      <div class="card-body">
        <%= action.desc %>
      </div>
    </div>
    <br>
  <% end %>
<% end %>

<% if not @monster.legendaries.empty? %>
  <strong>Legendary Actions:</strong>
  <% @monster.legendaries.each do |legendary|%>
    <div class="card">
      <div class="card-header">
        <%= legendary.name %>
      </div>
      <div class="card-body">
        <%= legendary.desc %>
      </div>
    </div>
    <br>
  <% end %>
<% end %>

app/views/monsters/index.html.erb
<h1>Monsters</h1>


<table class="table">
  <tr>
    <!--<th>Id</th>-->
    <th>Name</th>
  </tr>

  <% @monsters.each do |item| %>
      <tr>
        <!--<td><%= item.id %></td>-->
        <td><%= item.name %></td>
        <td><%= link_to 'Show', {id: item.id, action: "show"}, class: 'btn btn-primary' %></td>
     </tr>
  <% end %>
</table>

app/views/monsters/show.html.erb
<%= render @monster %>

app/views/npcs/_form.html.erb
<%= form_with(model: @npc, local: true) do |form| %>

  <% if @npc.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@npc.errors.count, "error") %> prohibited
        this NPC from being saved:
      </h2>
      <ul>
        <% @npc.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
  </p>

  <% if admin? %>
    <p>
      <%= form.check_box :discovered %>
      <%= form.label :Discovered %>
    </p>
  <% end %>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/npcs/_npc.html.erb

<h2><%= @npc.name %></h2>

<p>
  <strong>Text:</strong>
  <%= @npc.description %>
</p>

<% if not permitted(@npc.quests).empty? %>
  <p>
    <strong>Quests:</strong>
    <% permitted(@npc.quests).each do |quest| %>
      <br> <%= link_to quest.name, quest %>
    <% end %>
  </p>
<% end %>

<% if admin? %>
  <p>
    <strong>Discovered:</strong>
    <%= @npc.discovered.to_s %>
  </p>
<% end %>

app/views/npcs/edit.html.erb
<h2>Edit NPC</h2>

<%= render 'form' %>

<%= link_to 'Cancel', npcs_path %>

app/views/npcs/index.html.erb
<h1>NPCs</h1>

<%= render :partial => 'shared/table', locals: { items: @npcs, controller: "npcs" } %>

app/views/npcs/new.html.erb
<h2>New NPC</h2>

<%= render 'form' %>

<%= link_to 'Cancel', npcs_path %>

app/views/npcs/show.html.erb

<%= render @npc %>

<%= link_to 'Edit', edit_npc_path(@npc), class: 'btn btn-warning' %>
<%= link_to 'Back', npcs_path, class: 'btn btn-default' %>

app/views/quests/_form.html.erb
<%= form_with(model: @quest, local: true) do |form| %>

  <% if @quest.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@quest.errors.count, "error") %> prohibited this quest from being saved:
      </h2>
      <ul>
        <% @quest.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :Description, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <% if admin? %>

    <div class="field form-group">
      <%= form.label :npcs, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= form.fields_for :npcs, include_id: false do |npc_form| %>
          <%= npc_form.collection_select :id, Npc.order(:name), :id, :name, include_blank: true, class: 'col-sm-2 control-label'%>
          <br>
      <% end %>
      </div>
    </div>

    <div class="field form-group">
      <%= form.label :Discovered, class: 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= form.check_box :discovered %>
      </div>
    </div>

  <% end %>

  <div class="actions form-group">
   <div class="col-sm-2">
     <%= form.submit %>
   </div>
 </div>

<% end %>

app/views/quests/_quest.html.erb

<h2><%= @quest.name %></h2>

<p>
  <strong>Text:</strong>
  <%= @quest.description %>
</p>

<% if not permitted(@quest.npcs).empty? %>
  <p>
    <strong>Npcs:</strong>
    <% permitted(@quest.npcs).each do |npc| %>
      <br> <%= link_to npc.name, npc %>
    <% end %>
  </p>
<% end %>

<% if admin? %>
  <p>
    <strong>Discovered:</strong>
    <%= @quest.discovered.to_s %>
  </p>
<% end %>

app/views/quests/edit.html.erb
<h2>Edit Quest</h2>

<%= render 'form' %>

<%= link_to 'Cancel', quests_path %>

app/views/quests/index.html.erb
<h1>Quests</h1>

<%= render :partial => 'shared/table', locals: { items: @quests, controller: "quests" } %>

app/views/quests/new.html.erb
<h2>New Quest</h2>

<%= render 'form' %>

<%= link_to 'Cancel', quests_path %>

app/views/quests/show.html.erb

<%= render @quest %>

<%= link_to 'Edit', edit_quest_path(@quest), class: 'btn btn-warning' %>
<%= link_to 'Back', quests_path, class: 'btn btn-default' %>

app/views/spells/_spell.html.erb
<h2><%= @spell.name %></h2>

<% (@spell.attributes.reject {|k,v| k=="id" or k=="created_at" or k=="updated_at" or v==nil or v=="" } ).each do |key, value| %>
  <p>
    <strong><%= key %>:</strong>
    <%= value %>
  </p>
<% end %>

app/views/spells/index.html.erb
<h1>Spells</h1>


<table class="table">
  <tr>
    <!--<th>Id</th>-->
    <th>Name</th>
  </tr>

  <% @spells.each do |item| %>
      <tr>
        <!--<td><%= item.id %></td>-->
        <td><%= item.name %></td>
        <td><%= link_to 'Show', {id: item.id, action: "show"}, class: 'btn btn-primary' %></td>
     </tr>
  <% end %>
</table>

app/views/spells/show.html.erb
<%= render @spell %>

app/views/welcome/index.html.erb
<h2>Farewell, Chosen Undead. I remain here, and await thee.</h2>

</br>
<p>
  This site features <%= link_to 'Quests', controller: 'quests' %>, <%= link_to 'NPCs', controller: 'npcs' %>,
  and an authorized <%= link_to 'Master Login', action: 'login' %> mode.
</p>

app/views/welcome/login.html.erb
<h1>You are now in administrator mode.</h1>
<p><%= link_to 'Back', root_path %></p>