config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'welcome/login'

  resources :quests
  resources :npcs

  get 'spells', to: 'spells#index'
  get 'spells/:id', to: 'spells#show'

  get 'monsters', to: 'monsters#index'
  get 'monsters/:id', to: 'monsters#show'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :discovered, -> { where(discovered: true) }
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :actions
  has_many :legendaries
  has_many :specials

  accepts_nested_attributes_for :actions
  accepts_nested_attributes_for :legendaries
  accepts_nested_attributes_for :specials

  def experience
    lookup = {"1/8" => 25,"1/4" => 50,"1/2" => 100,"1" => 200,"2" => 450,"3" => 700,"4" => 1100,"5" => 1800,"6" => 2300,"7" => 2900,"8" => 3900,"9" => 5000,"10" => 5900,"11" => 7200,"12" => 8400,"13" => 10000,"14" => 11500,"15" => 13000,"16" => 15000,"17" => 18000,"18" => 20000,"19" => 22000,"20" => 25000,"21" => 33000,"22" => 41000,"23" => 50000,"24" => 62000,"30" => 155000}
    return lookup[challenge_rating]
  end

  validates_presence_of :name, :challenge_rating, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma
end

app/models/monster/action.rb
class Monster::Action < ApplicationRecord
  belongs_to :monster

  validates_presence_of :name, :desc
end

app/models/monster/special.rb
class Monster::Special < ApplicationRecord
  belongs_to :monster

  def damage_dice=(param)
  end
  
  validates_presence_of :name, :desc
end

app/models/npc.rb
class Npc < ApplicationRecord
  has_and_belongs_to_many :quests
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
  
end

app/models/quest.rb
class Quest < ApplicationRecord
  has_and_belongs_to_many :npcs
  accepts_nested_attributes_for :npcs
  validates :name, presence: true, length: { minimum: 2 }, uniqueness: true

  def npcs_attributes=(attributes)
    npc_ids = attributes.values.map {|hash| hash[:id] }
    npc_ids = npc_ids.select { |value| value != nil }
    self.npcs = Npc.where(id: npc_ids)
  end
end

app/models/spell.rb
class Spell < ApplicationRecord
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password|
        session[:user] = 'admin' if user_name == 'admin' && password == 'password'
      end
    end

    def admin?
      session[:user] == 'admin'
    end

    def requireAuth(item)
      if not admin? and not item.discovered
        authenticate
      end
    end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

  def index
    @monsters = Monster.all
  end

  def show
    @monster = Monster.find(params[:id])
    puts @monster.actions.empty?
    puts "aaaaaaaaaaaaaaaaaaaaaa"
  end

end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController

  def index
    @npcs = Npc.all
  end

  def show
    @npc = Npc.find(params[:id])
    requireAuth(@npc)
  end

  def new
    @npc = Npc.new()
  end

  def edit
    @npc = Npc.find(params[:id])
    requireAuth(@npc)
  end

  def create
    @npc = Npc.new(npc_params)

    if @npc.save
      redirect_to @npc
    else
      render 'new'
    end
  end

  def update
    @Npc = Npc.find(params[:id])
    requireAuth(@npc)

    if @Npc.update(npc_params)
      redirect_to @Npc
    else
      render 'edit'
    end
  end

  def destroy
    @Npc  = Npc.find(params[:id])
    requireAuth(@npc)

    @Npc.destroy
    redirect_to npcs_path
  end

  private
    def npc_params
      params.require(:npc).permit(:name, :description, :discovered)
    end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController

  def index
    @quests = Quest.all
  end

  def show
    @quest = Quest.find(params[:id])
    requireAuth(@quest)
  end

  def new
    @quest = Quest.new()
    2.times { @quest.npcs.build }
  end

  def edit
    @quest = Quest.find(params[:id])
    requireAuth(@quest)

    @quest.npcs.build
  end

  def create
    @quest = Quest.new(quest_params)

    if @quest.save
      redirect_to @quest
    else
      render 'new'
    end
  end

  def update
    @quest = Quest.find(params[:id])
    requireAuth(@quest)

    if @quest.update(quest_params)
      redirect_to @quest
    else
      render 'edit'
    end
  end

  def destroy
    @quest  = Quest.find(params[:id])
    requireAuth(@quest)

    @quest.destroy
    redirect_to quests_path
  end

  private
    def quest_params
      params.require(:quest).permit(:name, :description, :discovered, npcs_attributes: [:id])
    end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController

  def index
    @spells = Spell.all
  end

  def show
    @spell = Spell.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate, only: :login

  def index
  end

  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin?
    session[:user] == 'admin'
  end

  def permitted(model)
    if admin?
      return model
    else
      return model.discovered
    end
  end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnDTools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-brand">
        <%= link_to "DnD Tools", root_path, class: "navbar-brand" %>
      </div>

      <ul class="navbar-nav mr-auto">
        <li class="nav-item"> <%= link_to "Quests", quests_path, class: "nav-link" %> </li>
        <li class="nav-item"> <%= link_to "NPCs", npcs_path, class: "nav-link" %> </li>
        <li class="nav-item"> <%= link_to "Spells", spells_path, class: "nav-link" %> </li>
        <li class="nav-item"> <%= link_to "Monsters", monsters_path, class: "nav-link" %> </li>
      </ul>

      <% if user_signed_in? %>
        <div class="navbar-text"> Logged in as <strong><%= current_user.email %></strong>. </div>
      <% end %>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item"> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %> </li>
          <li class="nav-item"> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %> </li>
        <% else %>
          <li class="nav-item"><%= link_to "Sign up", new_user_registration_path, :class => 'nav-link'  %> </li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, :class => 'nav-link'  %> </li>
        <% end %>
        <!-- <li class="nav-item"> <%= link_to 'Master Login', welcome_login_path, class: "nav-link" %> </li> -->
      </ul>
    </nav>
    <br>

    <div id="main-container" class="container">
      <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>
      <% if alert %> <p class="alert alert-danger"><%= alert %></p> <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_table.html.erb

<table class="table">
  <tr>
    <!--<th>Id</th>-->
    <th>Name</th>
  </tr>

  <% permitted(items).each do |item| %>
      <tr>
        <!--<td><%= item.id %></td>-->
        <td><%= item.name %></td>
        <td><%= link_to 'Show', item, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', {id: item.id, action: 'edit'}, class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', item, {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'} %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Item', {controller: controller, action: 'new'}, class: 'btn btn-success' %>